# Generated by Django 2.2.5 on 2019-11-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Synlinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField()),
                ('pre_x', models.IntegerField()),
                ('pre_y', models.IntegerField()),
                ('pre_z', models.IntegerField()),
                ('post_x', models.IntegerField()),
                ('post_y', models.IntegerField()),
                ('post_z', models.IntegerField()),
                ('scores', models.FloatField()),
                ('segmentid_x', models.IntegerField(db_index=True)),
                ('segmentid_y', models.IntegerField(db_index=True)),
                ('max', models.IntegerField()),
                ('index', models.IntegerField()),
            ],
        ),
    ]
