# Generated by Django 2.2.8 on 2020-01-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitmap', '0002_auto_20200117_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synlinks',
            name='segmentid_x',
        ),
        migrations.RemoveField(
            model_name='synlinks',
            name='segmentid_y',
        ),
        migrations.AddField(
            model_name='synlinks',
            name='segmentid_post',
            field=models.BigIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synlinks',
            name='segmentid_pre',
            field=models.BigIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
